### ISSUE TITLE
KaOS 2015 Installation Bug

### ISSUE THREAD

**Issue by iNzz** [KaOSx/main#13]
Hello! I have a problem with KaOS while installing it.

What I do :

Create a Bootable Usb with KaOS 2015.ISO on it , have an 80gb hard disk,

Launch KaOS live , click for installation , select everything properly how i want it , KaOS installation begins, at the end , about 0.5 seconds away from the "creating user" text below the installation bar, an error occurs and it says:

------------------------------------------------------------

<b>Installation Failed</b>

Boost.Python error in job "Run script userkf5/main.py".

<b> class 'AttributeError' </b>

'Nonetype'object has no attribiute 'group'
Traceback:

File "/usr/lib/calamares/modules/userkf5/main.py" , line 121, in run print (m.group(0)).

------------------------------------------------------------

I also created a thread on 4chan.org , if you want to see the thread , here is the link!

http://boards.4chan.org/g/thread/47915533/kaos-install-bug

Ofcourse i checked the /userkf5/main.py and it seems to be a Python programming script , i checked line 121 and it's just this line:

print (m.group(0)).

What i tried to do:

Using octopi to install calamares (seems to be some sort of c/c++ compiler) , after i've installed it , the installation won't even begin.

Help?

**Comment by demmm** [comment]
This has nothing to do with any package in the Mian repo, installation questions should either be asked in the forum, or if you know it is a bug, report it in the live-iso issues:
https://github.com/KaOSx/live-uefi/issues
http://kaosx.us/phpBB3/viewforum.php?f=4

Partial updates are never supported in KaOS, so installing new calamares without updating leads to a broken calamares, that is absolutely no bug, just something that will never be supported in this distro.

You need to check if your md5sum is correct, if you created the live media in a way that is supported by this distro, if all those check out, follow the guidelines here:
http://kaosx.us/asking-and-reporting-the-smart-way/
to proper post an install log and further needed info.

Closing the issue here now, wrong place to further assist you.
